CREATE TABLE "GCG_4452_Prt_BFlush"(
 "PART" CHAR(17),
 "REV" CHAR(3),
 "LOCATION" CHAR(2),
 "PL" CHAR(2),
 "CODE_SORT" CHAR(10),
 "CODE_SOURCE" CHAR(12),
 "BACKFLUSH" BIT NOT NULL );

CREATE UNIQUE NOT MODIFIABLE INDEX "4452_Prt00" USING 0 ON "GCG_4452_Prt_BFlush"("PART", "REV", "LOCATION");